#!/bin/sh
# Just a one-liner to display the name of the network connected to and if no internet, then displays the appropriate icon

WIFINAME=$(nmcli -a | awk '/^wlp2s0/' | awk '{print $4}') # displays wifi name
WIFI=$(nmcli -a | awk '/^wlp2s0/' | awk '{print $2}') # shows connectivity to wifi

# Icons for WiFi and ethernet
# WiFi: 
# Ethernet: 
# No internet: 

if [ "$WIFI" = "connected" ]; then
		echo "  $WIFINAME "
else
		echo "  "
fi
