#!/bin/sh
# Script to provide battery information to dwm statusbar

battery() {
	CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)
	STATUS=$(cat /sys/class/power_supply/BAT0/status)

	if [ "$STATUS" = "Charging" ]; then
	   	echo "   $CHARGE% "
    else
		echo "   $CHARGE% "
    fi
}

battery
