#!/bin/sh

# Script that shows the brightness level on the status bar
BRI=$(($(cat /sys/class/backlight/amdgpu_bl0/brightness) * 100 / $(cat /sys/class/backlight/amdgpu_bl0/max_brightness) ))

# echo "  $BRI% "
echo "  $BRI% "
# echo "  $BRI% "
